# Validate this file using http://lint.travis-ci.org/
language: python
sudo: false
cache:
  directories:
    - $HOME/.cache/pip
python:
  - "2.7"
  - "3.5"
install:
  - python setup.py install
script: python setup.py test
